#### Values to be changed
qTestManager:
  client:
    jdbc:
      postgresUrl: jdbc:postgresql://psql-postgresql/qTest
      postgresUserName: postgres
      postgresPassword: postgres
      postgresReadOnlyUrl: jdbc:postgresql://psql-postgresql/qTest
      postgresReadOnlyUserName: postgres
      postgresReadOnlyPassword: postgres
      sslEnable: false
      sslMountPath: "/etc/ssl"
      sslPath: "?ssl=true&sslmode=verify-full&sslrootcert=/etc/ssl/root.crt"
      rootCRT: ""
  mail:
    host: "smtp.local"
    port: 465
    userName: "qtest"
    password: cG9zdGdyZXM=
    supportEmailAddress: supports@tricentis.com
  elasticSearch:
    init: false
    disable: false
    scheme: http
    host: elasticsearch.local
    port: 9200
    permittedClients: ""
  notification:
    urlExternal: https://mgr-service.500c00ae4fa24c86bda7.westus2.aksapp.io
  preUrl: http://<sitename>.qtest.local
  preUrlHttps: https://<sitename>.qtest.local
  pulseUrlBase: "http://localhost:8080"  
  attachmentFolderPath: /mnt/data/qtest/attachments
  licenseFolderPath: /mnt/data/qtest/license
  qtest:
    request:
      nonce:
        disabled: true
        mode: HighPrecision
  security:
    csrf:
      source:
        trust:
          pattern: ""
  cors:
    allowed:
      all: true
      domains: ""
  blobStorage:
    type: disk_storage

limitRange:
  enabled: true
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95
  limits:
    - max:
        cpu: "1"
        memory: 3Gi
      default:
        cpu: "1"
        memory: 3Gi
      defaultRequest:
        cpu: "1"
        memory: 3Gi
      type: Container

persistence:
  accessMode: ReadWriteOnce
  size: 10Gi

secrets:
  enabled: true

# Ingress
ingressClass:
  enabled: false

ingress:
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
  - mgr-service.500c00ae4fa24c86bda7.westus2.aksapp.io
  paths: []
  extraPaths:
    - path: /
      pathType: Prefix
      backendServiceName: mgr-service
      backendPort: 8080
  tls:
  - hosts:
    - mgr-service.500c00ae4fa24c86bda7.westus2.aksapp.io

# HPA values
autoscaling:
  enabled: false
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95
  minReplicas:
    ui: 1
    api: 0
    notification: 0
    poller: 0
    default: 1

# Where are your images?
image:
  repository: tricentisimage/qtest-mgr
  liquibase: tricentisimage/qtest-mgr-liquibase
  pullPolicy: IfNotPresent
  tag: 11.0.5-f41702f
  liquibasetag: 11.0.5-f41702f
imageCredentials:
  enabled: true
  existingImageCredentials: regcred
testconductor:
  environment:
    isOnPremise: true
    singleInstance: true
