qTestLaunch:
  qTestLaunchDBName: qTest
  qTestLaunchDBUserName: postgres
  qTestLaunchDBPwd: cG9zdGdyZXM=
  qTestLaunchDBHostName: host.docker.internal
  qTestLaunchRootURL: https://launch.qtest.local
  qTestLaunchQTestURL: http://mgr-service:8080
  qTestLaunchNodeTLSRejectUnAuthorized: "0"
  qTestLaunchTCPWD: "qTest"
  qTestLaunchPort: "3080"
  qTestLaunchDBSSLEnable: false
  qTestLaunchDBSSLMountPath: "/etc/ssl"
  qTestLaunchDBSSL: "?ssl=true&sslmode=verify-full&sslrootcert=/etc/ssl/root.crt"
  qTestLaunchDBRootCRT: ""

# ************** Don't modify below values ***********************
secrets:
  enabled: true

service:
  type: ClusterIP
  port: 3080
  targetPort: 3080
  serviceName: qtest-launch-service


ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
    - launch.qtest.local
  paths:
    - path: /
      pathType: Prefix
      backendServiceName: qtest-launch-service
      backendPort: 3080
  extraPaths: []
  tls:
    - hosts:
        - launch.qtest.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
