#### Values to be changed
qTestManager:
  client:
    jdbc:
      postgresUrl: jdbc:postgresql://psql-postgresql/qTest
      postgresUserName: postgres
      postgresPassword: postgres
      postgresReadOnlyUrl: jdbc:postgresql://psql-postgresql/qTest
      postgresReadOnlyUserName: postgres
      postgresReadOnlyPassword: postgres
      sslEnable: false
      sslMountPath: "/etc/ssl"
      sslPath: "?ssl=true&sslmode=verify-full&sslrootcert=/etc/ssl/root.crt"
      rootCRT: ""
  mail:
    host: "smtp.local"
    port: 465
    userName: "qtest"
    password: cG9zdGdyZXM=
    supportEmailAddress: supports@tricentis.com
  elasticSearch:
    init: false
    disable: false
    scheme: http
    host: elasticsearch.local
    port: 9200
    permittedClients: ""
  notification:
    urlExternal: https://nephele.qtest.local
  preUrl: http://<sitename>.qtest.local
  preUrlHttps: https://<sitename>.qtest.local
  pulseUrlBase: "http://localhost:8080"  
  attachmentFolderPath: /mnt/data/qtest/attachments
  licenseFolderPath: /mnt/data/qtest/license
  qtest:
    request:
      nonce:
        disabled: true
        mode: HighPrecision
  security:
    csrf:
      source:
        trust:
          pattern: ""
  cors:
    allowed:
      all: true
      domains: ""
  blobStorage:
    type: disk_storage

ingress:
  className: nginx
  hosts:
  - nephele.qtest.local
  paths: []
  extraPaths:
    - path: /
      pathType: Prefix
      backendServiceName: mgr-service
      backendPort: 8080
  tls:
  - hosts:
    - nephele.qtest.local

limitRange:
  enabled: true
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95
  limits:
    - max:
        cpu: "1"
        memory: 3Gi
      default:
        cpu: "1"
        memory: 3Gi
      defaultRequest:
        cpu: "1"
        memory: 3Gi
      type: Container

persistence:
  accessMode: ReadWriteOnce
  size: 10Gi

# ************** Don't modify below values ***********************
# Setup Ingress with TLS
secrets:
  enabled: true

# Your desktop doesn't have an LB
service:
  type: ClusterIP

ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

# HPA values
autoscaling:
  enabled: false
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95
  minReplicas:
    ui: 1
    api: 0
    notification: 0
    poller: 0
    default: 1

# Where are your images?
image:
  repository: localhost:5000/qtestmgr
  liquibase: localhost:5000/liquibase
  pullPolicy: Always
  tag: latest
  liquibasetag: latest
imageCredentials:
  enabled: true
  existingImageCredentials: regcred
testconductor:
  environment:
    singleInstance: true
