# Setup your replica count!
autoscaling:
  enabled: true
  minReplicas:
    ui: 1
    api: 1
    notification: 0
    poller: 0

limitRange:
  enabled: true
  limits:
    - max:
        cpu: '1'
        memory: 2Gi
      default:
        cpu: '1'
        memory: 2Gi
      defaultRequest:
        cpu: '1'
        memory: 2Gi
      type: Container


# Where are your images?
image:
  repository: localhost:5000/qtestmgr
  liquibase: localhost:5000/liquibase
  pullPolicy: IfNotPresent
  tag: latest
  liquibasetag: latest

# Setup Ingress with TLS
secrets:
  enabled: true

# Your desktop doesn't have an LB
service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
  - nephele.qtest.local
  - qtestdev1.qtest.local
  tls:
  - secretName: qtest-tls-secret
    hosts:
    - nephele.qtest.local
  annotations: null

# qTest Manager
qTestManager:
  client:
    jdbc:
      postgresUrl: jdbc:postgresql://host.docker.internal/qTest
      postgresUserName: postgres
      postgresPassword: cG9zdGdyZXM=
      postgresReadOnlyUrl: jdbc:postgresql://host.docker.internal/qTest
      postgresReadOnlyUserName: postgres
      postgresReadOnlyPassword: cG9zdGdyZXM=
  notification:
    urlExternal: https://nephele.qtest.local
  preUrl: http://<sitename>.qtest.local
  preUrlHttps: https://<sitename>.qtest.local
  attachmentFolderPath: /mnt/data/qtest/attachments
  licenseFolderPath: /mnt/data/qtest/license

# Turn off persistence
persistence:
  enabled: false

testconductor:
  environment:
    isOnPremise: true
