apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-chart-limit-range
spec:
  limits:
    - default:          # Default container limit
        cpu: 500m
        memory: 1Gi
      defaultRequest:   # Default container request
        cpu: 200m
        memory: 1Gi
      max:              # Max container limit
        cpu: 1
        memory: 2Gi
      min:              # Min container request
        cpu: 100m
        memory: 100Mi
      type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-chart-resource-quota
spec:
  hard:
    limits.cpu: 48
    limits.memory: 64Gi
    requests.cpu: 40.8
    requests.memory: 54.4Gi
    pods: 20
    persistentvolumeclaims: 25
    requests.storage: 200Gi
